"""
setup_env.py
============
Step 2 — Interactively create the .env file from .env.example.
Safe to re-run; will ask before overwriting an existing .env.

Usage:
    python setup_env.py
    python setup_env.py --non-interactive   # uses all defaults (local dev)
"""

from __future__ import annotations

import argparse
import os
import sys

ENV_FILE     = os.path.join(os.path.dirname(__file__), ".env")
EXAMPLE_FILE = os.path.join(os.path.dirname(__file__), ".env.example")

FIELDS = [
    # (key, prompt, default)
    ("POSTGRES_HOST",     "PostgreSQL host",          "localhost"),
    ("POSTGRES_PORT",     "PostgreSQL port",          "5432"),
    ("POSTGRES_DB",       "PostgreSQL database name", "sales_db"),
    ("POSTGRES_USER",     "PostgreSQL username",      "postgres"),
    ("POSTGRES_PASSWORD", "PostgreSQL password",      "postgres"),
    ("AWS_ACCESS_KEY_ID",     "AWS Access Key ID     (leave blank to skip S3)", ""),
    ("AWS_SECRET_ACCESS_KEY", "AWS Secret Access Key (leave blank to skip S3)", ""),
    ("AWS_REGION",        "AWS region",               "us-east-1"),
    ("S3_BUCKET",         "S3 bucket name",           "sales-etl-pipeline"),
]


def write_env(values: dict[str, str]) -> None:
    lines = ["# Auto-generated by setup_env.py — do NOT commit this file\n"]
    for key, val in values.items():
        lines.append(f"{key}={val}\n")
    with open(ENV_FILE, "w") as f:
        f.writelines(lines)
    print(f"\n✓  .env written to: {ENV_FILE}")


def main():
    parser = argparse.ArgumentParser(description="Create .env file")
    parser.add_argument(
        "--non-interactive", action="store_true",
        help="Use all default values (good for local dev / CI)"
    )
    args = parser.parse_args()

    # ── Warn if .env already exists ──────────────────────────────────────────
    if os.path.exists(ENV_FILE) and not args.non_interactive:
        answer = input(".env already exists. Overwrite? [y/N]: ").strip().lower()
        if answer != "y":
            print("Skipped — existing .env kept.")
            return

    values: dict[str, str] = {}

    if args.non_interactive:
        for key, _, default in FIELDS:
            values[key] = default
        print("Using all default values (non-interactive mode)")
    else:
        print("=" * 60)
        print("  Sales ETL Pipeline — Environment Setup")
        print("  Press Enter to accept the default shown in [brackets]")
        print("=" * 60)
        for key, prompt, default in FIELDS:
            display_default = f"[{default}]" if default else "[leave blank]"
            raw = input(f"\n{prompt} {display_default}: ").strip()
            values[key] = raw if raw else default

    write_env(values)

    # ── Reminder about .gitignore ────────────────────────────────────────────
    print("\n⚠   Make sure .env is in your .gitignore (it already is in this project)")
    print("    Never commit AWS credentials or passwords to Git.\n")


if __name__ == "__main__":
    main()
